# Generated by Django 4.2.4 on 2023-08-07 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='PAN_Number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part_Name', models.CharField(max_length=100)),
                ('Part_Quantity', models.PositiveIntegerField()),
                ('Cost_Price', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('Part_Number', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garage.supplier')),
            ],
        ),
    ]
