# Generated by Django 4.2.4 on 2023-08-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0002_alter_supplier_pan_number_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Feedback', models.CharField(max_length=1500)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
