# Generated by Django 4.2.4 on 2023-08-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_Email', models.CharField(max_length=100)),
                ('Customer_PhoneNumber', models.CharField(max_length=100)),
                ('Customer_Profession', models.CharField(max_length=100)),
                ('Bike_Model_Name', models.CharField(max_length=100)),
                ('Preferred_Date', models.DateField(blank=True, null=True)),
                ('Customer_Address', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(choices=[('Bike Service', 'Bike Service'), ('Bike Repair', 'Bike Repair')], default=' ', max_length=20)),
                ('Order_Status', models.CharField(blank=True, choices=[('Pending', 'PENDING'), ('Request_Accepted', 'REQUEST_ACCEPTED'), ('Request_Canceled', 'REQUEST_CANCELED')], default='Pending', max_length=20, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True, verbose_name='DateTime')),
            ],
        ),
    ]
