# Generated by Django 4.2.4 on 2023-08-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0005_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Total_Amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
