# Generated by Django 4.2.4 on 2023-08-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0006_alter_sales_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Part_Number',
            field=models.CharField(max_length=100),
        ),
    ]
