# Generated by Django 4.2.4 on 2023-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0007_alter_stock_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
