# Generated by Django 4.2.4 on 2023-08-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0009_alter_sales_date_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
