# Generated by Django 4.2.4 on 2023-08-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0010_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
