# Generated by Django 4.2.4 on 2023-08-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0011_alter_stock_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phonenumber', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('chasis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bike_model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('ODO_meter_reading', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('Bike Service', 'Bike Service'), ('Bike Repair', 'Bike Repair')], default=' ', max_length=20)),
                ('issued_DateTime', models.DateTimeField()),
                ('DeliveryDateTime', models.DateTimeField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Part_Number', models.CharField(max_length=100)),
                ('Unit_Price', models.FloatField()),
                ('Quantity', models.PositiveIntegerField()),
                ('Total_Amount', models.FloatField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Part_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garage.stock')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_bills', to='Garage.jobcard')),
            ],
        ),
    ]
