# Generated by Django 4.2.4 on 2023-08-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0013_gallery_pathivara_infos_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='Preferred_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
