# Generated by Django 4.2.4 on 2023-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0014_alter_servicerequest_preferred_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='DateTime'),
        ),
    ]
