# Generated by Django 4.2.4 on 2023-09-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0015_alter_servicerequest_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
