# Generated by Django 4.2.4 on 2023-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0016_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Bike_Model', models.CharField(max_length=100)),
                ('Service_Type', models.CharField(max_length=100)),
                ('Feedback', models.CharField(max_length=1500)),
                ('Order_Status', models.CharField(blank=True, choices=[('Pending', 'PENDING'), ('Review_Done', 'REVIEW_DONE')], default='Pending', max_length=20, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
