# Generated by Django 4.2.4 on 2023-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0017_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Feedback',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
