# Generated by Django 4.2.4 on 2023-09-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0018_alter_review_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Order_Status',
            new_name='Review_Status',
        ),
        migrations.AddField(
            model_name='review',
            name='Customer_Phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='registration_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
