# Generated by Django 4.2.4 on 2023-09-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0020_debenture_alter_review_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debenture',
            old_name='Reason',
            new_name='Remarks',
        ),
    ]
