# Generated by Django 4.2.4 on 2023-09-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0021_rename_reason_debenture_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='jobcard_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='ODO_meter_reading',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='bike_model',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='chasis_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='customer_phonenumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='engine_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='registration_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockbill',
            name='Part_Number',
            field=models.CharField(max_length=200),
        ),
    ]
