# Generated by Django 4.2.4 on 2023-09-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0022_jobcard_jobcard_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
