# Generated by Django 4.2.4 on 2023-09-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0023_jobcard_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
