# Generated by Django 4.2.4 on 2023-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0024_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
