# Generated by Django 4.2.4 on 2023-09-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0025_alter_jobcard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='DateTime'),
        ),
    ]
