# Generated by Django 4.2.4 on 2023-09-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0027_review_follow_up_status_review_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Follow_up_Status',
            field=models.CharField(blank=True, choices=[('Pending', 'PENDING'), ('Follow_up_Done', 'FOLLOW_UP_DONE')], default='Pending', max_length=20, null=True),
        ),
    ]
