# Generated by Django 4.2.4 on 2023-09-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0028_alter_review_follow_up_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathivara_infos',
            name='Website_desc',
            field=models.TextField(null=True),
        ),
    ]
