# Generated by Django 3.2.21 on 2023-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garage', '0029_alter_pathivara_infos_website_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='service_type',
            field=models.CharField(choices=[('Paid Service', 'Paid Service'), ('Accidental', 'Accidental'), ('AMC', 'AMC'), ('QRC', 'QRC')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('Paid Service', 'Paid Service'), ('Accidental', 'Accidental'), ('AMC', 'AMC'), ('QRC', 'QRC')], default=' ', max_length=20),
        ),
    ]
